/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tictactoe;

import javax.swing.JButton;
import javax.swing.JOptionPane;

public class GameFrame extends javax.swing.JFrame {

    private Player currentPlayer;
    private GameLogic gameLogic;
    private PlayerService playerService;
    private JButton[] buttons;

    public GameFrame(Player player) {
        this.currentPlayer = player;
        this.gameLogic = new GameLogic();
        this.playerService = new PlayerService();
        initComponents();
        
        this.setTitle("Tic Tac Toe - Player: " + currentPlayer.getUsername());
        buttons = new JButton[]{btn0, btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8};
    }

    public GameFrame () {
        initComponents();
        pack();
        setLocationRelativeTo(null);
    }
    
    private void handleButtonClick(int index) {
        if (gameLogic.makeMove(index, 'X')) {
            buttons[index].setText("X");
            
            if (gameLogic.checkWinner('X')) {
                endGame("WIN");
                return;
            }
            if (gameLogic.isDraw()) {
                endGame("DRAW");
                return;
            }

            int compIndex = gameLogic.computerMove();
            if (compIndex != -1 && gameLogic.makeMove(compIndex, 'O')) {
                buttons[compIndex].setText("O");
                
                if (gameLogic.checkWinner('O')) {
                    endGame("LOSE");
                    return;
                }
                if (gameLogic.isDraw()) {
                    endGame("DRAW");
                    return;
                }
            }
        }
    }

    private void endGame(String result) {
        playerService.updateStatistics(currentPlayer, result);
        
        if (result.equals("WIN")) {
            JOptionPane.showMessageDialog(this, "You Win! +10 Points");
        } else if (result.equals("LOSE")) {
            JOptionPane.showMessageDialog(this, "You Lose! 0 Points");
        } else {
            JOptionPane.showMessageDialog(this, "It's a Draw! +3 Points");
        }
        
        MainMenuFrame menu = new MainMenuFrame(currentPlayer);
        menu.setVisible(true);
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game");
        setResizable(false);

        btn0.setBackground(new java.awt.Color(151, 103, 115));
        btn0.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btn0.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn0.setBorderPainted(false);
        btn0.addActionListener(this::btn0ActionPerformed);

        btn1.setBackground(new java.awt.Color(151, 103, 115));
        btn1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btn1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn1.setBorderPainted(false);
        btn1.addActionListener(this::btn1ActionPerformed);

        btn2.setBackground(new java.awt.Color(151, 103, 115));
        btn2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btn2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn2.setBorderPainted(false);
        btn2.addActionListener(this::btn2ActionPerformed);

        btn3.setBackground(new java.awt.Color(151, 103, 115));
        btn3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btn3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn3.setBorderPainted(false);
        btn3.addActionListener(this::btn3ActionPerformed);

        btn4.setBackground(new java.awt.Color(151, 103, 115));
        btn4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btn4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn4.setBorderPainted(false);
        btn4.addActionListener(this::btn4ActionPerformed);

        btn5.setBackground(new java.awt.Color(151, 103, 115));
        btn5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btn5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn5.setBorderPainted(false);
        btn5.addActionListener(this::btn5ActionPerformed);

        btn6.setBackground(new java.awt.Color(151, 103, 115));
        btn6.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btn6.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn6.setBorderPainted(false);
        btn6.addActionListener(this::btn6ActionPerformed);

        btn7.setBackground(new java.awt.Color(151, 103, 115));
        btn7.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btn7.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn7.setBorderPainted(false);
        btn7.addActionListener(this::btn7ActionPerformed);

        btn8.setBackground(new java.awt.Color(151, 103, 115));
        btn8.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btn8.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn8.setBorderPainted(false);
        btn8.addActionListener(this::btn8ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        handleButtonClick(0);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        handleButtonClick(1);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        handleButtonClick(2);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        handleButtonClick(3);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        handleButtonClick(4);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        handleButtonClick(5);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        handleButtonClick(6);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        handleButtonClick(7);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        handleButtonClick(8);
    }//GEN-LAST:event_btn8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameFrame(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    // End of variables declaration//GEN-END:variables
}
